2021-12-03 22:40:21,120 ERROR: Exception on / [GET] [in C:\Users\Миша\PycharmProjects\VIT 2.0\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\Миша\PycharmProjects\VIT 2.0\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Миша\PycharmProjects\VIT 2.0\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Миша\PycharmProjects\VIT 2.0\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Миша\PycharmProjects\VIT 2.0\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Миша\PycharmProjects\VIT 2.0\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Миша\PycharmProjects\VIT 2.0\app\routes.py", line 28, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "C:\Users\Миша\PycharmProjects\VIT 2.0\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Миша\PycharmProjects\VIT 2.0\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Миша\PycharmProjects\VIT 2.0\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Миша\PycharmProjects\VIT 2.0\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Миша\PycharmProjects\VIT 2.0\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Миша\PycharmProjects\VIT 2.0\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Миша\PycharmProjects\VIT 2.0\app\templates\base.html", line 32, in template
    {% endblock $}
jinja2.exceptions.TemplateSyntaxError: unexpected char '$' at 1265
2021-12-03 22:44:09,692 INFO: Microblog startup [in C:\Users\Миша\PycharmProjects\VIT 2.0\app\__init__.py:47]
2021-12-03 22:44:43,276 INFO: Microblog startup [in C:\Users\Миша\PycharmProjects\VIT 2.0\app\__init__.py:47]
